apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend-checkvariable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamwizard-backend-checkvariable
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend-checkvariable
    spec:
      containers:
        - name: streamwizard-backend-checkvariable
          image: ghcr.io/streamerbuddybot/checkvariable:b2195296c0cf27841ec442b005ac790a4c72d6fd
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: streamwizard-backend
          volumeMounts:
            - name: grpc-dns
              mountPath: /usr/src/app/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: grpc-dns
          configMap:
            name: grpc-dns
